### ISSUE TITLE
网页的IP归属地信息无法显示: cannot found mmdb file

### ISSUE THREAD

**Issue by 96368a** [lanthora/cacao#87]
**Describe the bug**
客户端连接服务器后，服务器报错 "cannot found mmdb file: file does not exist"，导致网页的IP归属地信息无法显示。

**To Reproduce**
1. 连接客户端到服务器。
2. 服务器返回错误信息 "cannot found mmdb file: file does not exist"。
3. 网页的IP归属地信息未显示。

**Expected behavior**
服务器应正常加载.mmdb文件，并显示网页的IP归属地信息。

**Screenshots**
![服务器报错](https://github.com/user-attachments/assets/c792b95d-bbbe-4182-8a13-9735bf0ca437)
![IP归属地未显示](https://github.com/user-attachments/assets/5cb6ad4f-3517-4a4a-95a4-205cdfb546ee)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser: [Chrome]
 - Version: [95.0.4638.69]

**Smartphone (please complete the following information):**
 - Device: [请填写设备型号，例如：iPhone 12]
 - OS: [请填写操作系统，例如：iOS 14.5]
 - Browser: [请填写浏览器，例如：Safari]
 - Version: [请填写浏览器版本，例如：14.1]

**Additional context**
服务器使用docker-compose运行
配置如下
```
version: '3.8'

services:
  cacao:
    image: lanthora/cacao
    container_name: cacao
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data:/var/lib/cacao
    command: ["--loglevel=debug", "--storage=/var/lib/cacao"]

**Comment by 96368a** [comment]
自行下载[GeoLite.mmdb项目](https://github.com/P3TERX/GeoLite.mmdb/releases)的GeoLite2-City.mmdb放入storage文件夹下面之后ip归属地恢复正常显示

**Comment by lanthora** [comment]
@96368a 用户有可能拿到精确度更高的数据库，所以没有自动下载数据库。目前没有考虑好怎么上传数据库，可以考虑在管理员页面上传；或者输入一个链接，服务端从后台下载这个链接里的文件，甚至能做成每天自动下载最新版。如果你有想法可以发个 PR
